### PR TITLE
Don't silence test failures (when -q)

### LINKED ISSUE #339: Failed tests are silenced when `-q` is used
### Summary

The `-q` option hides failed tests from output

### PoC

```
$ make test-without-building
xcodebuild test \
		-project TrueArt.xcodeproj \
		-scheme TrueArt \
		-destination 'id=06F2A4D5-640C-4774-80FF-2CBB073856A4' \
		-parallel-testing-enabled NO \
		DEVELOPMENT_TEAM=SSY9UMBZ4Q | xcbeautify --disable-logging
Resolving Package Graph
Resolved source packages
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:06F2A4D5-640C-4774-80FF-2CBB073856A4, OS:18.1, name:iPhone 16 Pro }
{ platform:iOS Simulator, id:06F2A4D5-640C-4774-80FF-2CBB073856A4, OS:18.1, name:iPhone 16 Pro }
[GRDB_GRDB] Processing empty-GRDB_GRDB.plist
[TrueArt] Processing empty-TrueArt.plist
[TrueArtTests] Processing empty-TrueArtTests.plist
Signing TrueArtTests.xctest (in target 'TrueArtTests' from project 'TrueArt')
Signing TrueArt.debug.dylib (in target 'TrueArt' from project 'TrueArt')
Signing __preview.dylib (in target 'TrueArt' from project 'TrueArt')
Signing TrueArt.app (in target 'TrueArt' from project 'TrueArt')
All tests
Test Suite 'All tests' passed at 2024-12-09 11:40:48.581.
Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test run started.
Suite MediaTests started
    ✔ persistence() (0.002 seconds)
    ⚠️  Test qq() recorded an issue at MediaTests.swift:15:9: Expectation failed: true == false
    ✖ qq() (0.001 seconds) 1 issue(s)
Suite MediaTests failed after 0.004 seconds with 1 issue(s)
Suite TrueArtTests started
    ✔ example() (0.001 seconds)
Suite TrueArtTests passed after 0.001 seconds
Test run with 3 tests failed after 0.004 seconds with 1 issue(s)
2024-12-09 11:40:56.675 xcodebuild[46213:35185203] [MT] IDETestOperationsObserverDebug: 16.317 elapsed -- Testing started completed.
2024-12-09 11:40:56.675 xcodebuild[46213:35185203] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2024-12-09 11:40:56.675 xcodebuild[46213:35185203] [MT] IDETestOperationsObserverDebug: 16.317 sec, +16.317 sec -- end
Failing tests:
	MediaTests.qq()

** TEST FAILED **

Testing started
```

```
$ make test-without-building
xcodebuild test \
		-project TrueArt.xcodeproj \
		-scheme TrueArt \
		-destination 'id=06F2A4D5-640C-4774-80FF-2CBB073856A4' \
		-parallel-testing-enabled NO \
		DEVELOPMENT_TEAM=SSY9UMBZ4Q | xcbeautify --disable-logging -q
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:06F2A4D5-640C-4774-80FF-2CBB073856A4, OS:18.1, name:iPhone 16 Pro }
{ platform:iOS Simulator, id:06F2A4D5-640C-4774-80FF-2CBB073856A4, OS:18.1, name:iPhone 16 Pro }
Test Suite 'All tests' passed at 2024-12-09 11:41:16.832.
Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test run started.
Suite MediaTests failed after 0.005 seconds with 1 issue(s)
Suite TrueArtTests started
Suite TrueArtTests passed after 0.001 seconds
Test run with 3 tests failed after 0.006 seconds with 1 issue(s)
2024-12-09 11:41:24.890 xcodebuild[46506:35194926] [MT] IDETestOperationsObserverDebug: 16.319 elapsed -- Testing started completed.
2024-12-09 11:41:24.891 xcodebuild[46506:35194926] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2024-12-09 11:41:24.891 xcodebuild[46506:35194926] [MT] IDETestOperationsObserverDebug: 16.319 sec, +16.319 sec -- end
Failing tests:
	MediaTests.qq()

** TEST FAILED **
```

### Suggested Regex

_No response_

### Suggested Output

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by case**
Closes #339. Similar to https://github.com/cpisciotta/xcbeautify/pull/29

### CODE REVIEW

**Comment by case** [comment]
@cpisciotta let me know if anything else is needed here! Happy to help on this.

File: Sources/XcbeautifyLib/CaptureGroups.swift [hunk 1]
```diff
@@ -1868,7 +1868,7 @@ struct SwiftMergeGeneratedHeadersCaptureGroup: CaptureGroup {
 }
 
 struct SwiftTestingIssueArgumentCaptureGroup: CaptureGroup {
-    static let outputType: OutputType = .testCase
+    static let outputType: OutputType = .error
```
Comment (cpisciotta) [inline Sources/XcbeautifyLib/CaptureGroups.swift]: Hmm... I don't think changing this to `error` is what we want. For now, what about a new `case`, like `testCaseError` or `testCaseFailure`? With that change, we'd want to split the `testCase` `OutputType`s to `testCasePass` or `testCaseSuccess` too.

Comment (case) [reply Sources/XcbeautifyLib/CaptureGroups.swift]: Sure thing! I just pushed a commit to address your feedback here.

File: Sources/XcbeautifyLib/CaptureGroups.swift
Comment (cpisciotta) [inline Sources/XcbeautifyLib/CaptureGroups.swift]:
```suggestion
    static let outputType: OutputType = .testCaseFailure
```

File: Sources/XcbeautifyLib/CaptureGroups.swift [hunk 2]
```diff
@@ -1306,7 +1306,7 @@ struct ParallelTestCasePassedCaptureGroup: CaptureGroup, JUnitParallelReportable
 }
 
 struct ParallelTestCaseSkippedCaptureGroup: CaptureGroup, JUnitParallelReportable {
-    static let outputType: OutputType = .testCase
+    static let outputType: OutputType = .testCaseSkip
 
     /// Regular expression captured groups:
     /// $1 = suite
```
[the remark this answers is not in the document]
Comment (cpisciotta) [reply Sources/XcbeautifyLib/CaptureGroups.swift:1312]: #492

**Comment by cpisciotta** [comment]
Thanks for your contribution @case! I modified the implementation slightly to handle certain cases differently (e.g. skipped tests).

Otherwise, LGTM, and I appreciate your contribution! Let me know if that does the trick.

**Comment by case** [comment]
> Thanks for your contribution @case! I modified the implementation slightly to handle certain cases differently (e.g. skipped tests).
> 
> Otherwise, LGTM, and I appreciate your contribution! Let me know if that does the trick.

Sounds good! I really appreciate your work on this project :)

Cheers,
-Eric
